"""initial

Revision ID: f1602fee3906
Revises: 
Create Date: 2026-05-18 17:49:12.327883
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f1602fee3906'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_post_mappings',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'post_id', name='uq_event_post')
    )
    op.create_index(op.f('ix_event_post_mappings_event_id'), 'event_post_mappings', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_post_mappings_post_id'), 'event_post_mappings', ['post_id'], unique=False)
    op.create_table('events',
    sa.Column('post_type', sa.String(length=20), nullable=True),
    sa.Column('source_author', sa.String(length=200), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('source_media', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('direct_content', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('operator_comment', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('intensity', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_event_post_mappings_post_id'), table_name='event_post_mappings')
    op.drop_index(op.f('ix_event_post_mappings_event_id'), table_name='event_post_mappings')
    op.drop_table('event_post_mappings')
    # ### end Alembic commands ###
